"""Explicit DEBUG: real graph equivalence/L0 profiling + synthetic full loss on CUDA.

Selected records are diagnostic inputs only, never a final training subset.
Every node/edge generated by the unchanged view rule is used. No weights saved.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import copy
import json
from pathlib import Path
import sys
import time

ROOT=Path(__file__).resolve().parents[1]
sys.path[:0]=[str(ROOT),str(ROOT/'tests')]


def main():
    import torch
    from hiercp_v2.data import materialize as old_materialize,collate as old_collate
    from hiercp_v2.model import PromptGraphModel as OldModel,context_descriptor as old_descriptor
    from hiercp_v2.storage import load_record as old_load
    from hiercp_v2.contracts import load_config as old_config
    from hiercp_v22.contracts import load_config,verify_v1,write_new,source_identity,sha,safe_new_root
    from hiercp_v22.migration import convert_record
    from hiercp_v22.data import materialize,collate,LocalBatch
    from hiercp_v22.storage import GraphWriter,load_record
    from hiercp_v22.model import PromptGraphModel,context_descriptor,prompt_loss
    from hiercp.preparation_runtime import snapshot
    from test_prompt_graph_v22_debug import fixtures
    from test_prompt_graph_v2_debug import memory_fixture
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--cache-root',type=Path,required=True)
    p.add_argument('--records',nargs='+',required=True,help='Explicit DEBUG records, each complete graph')
    p.add_argument('--output',type=Path,required=True)
    args=p.parse_args();verify_v1();cfg,base=load_config();oc,ob=old_config()
    if not torch.cuda.is_available():raise RuntimeError('CUDA required; no fallback')
    torch.set_num_threads(4)
    root=safe_new_root(args.output);device=torch.device('cuda');resources=snapshot()
    hashes={r:sha(args.cache_root/r) for r in args.records}
    writer=GraphWriter(root,minimum_free_bytes=0) # DEBUG-only temporary copies, not production storage.
    started=time.perf_counter()
    def read(relative):
        before=old_load(args.cache_root,relative);after=convert_record(before)
        saved=writer.write(relative,after,(before['case_id'],before.get('donor_case_id',before['case_id']),before['component_id']))
        restored=load_record(root,saved['path'])
        old=old_materialize(before);new=materialize(restored)
        for kind in old[0].node_types:
            for key,value in old[0][kind].items():
                if torch.is_tensor(value):torch.testing.assert_close(value,new[0][kind][key],rtol=0,atol=0)
        for edge in old[0].edge_types:
            for key,value in old[0][edge].items():
                if torch.is_tensor(value):torch.testing.assert_close(value,new[0][edge][key],rtol=0,atol=0)
        if 'source_patch' in restored or 'target_patch' in restored:raise RuntimeError('Dense patches leaked into v2.2 storage')
        return old,new,{'path':relative,'nodes':old[0].num_nodes,
                        'edges':sum(old[0][e].edge_index.shape[1] for e in old[0].edge_types),
                        'source_sha256':hashes[relative],'converted_sha256':saved['sha256']}
    with ThreadPoolExecutor(max_workers=4) as pool:items=list(pool.map(read,args.records))
    preparation_seconds=time.perf_counter()-started
    for start in range(0,len(items),2):
        old=old_collate([(r[0],i) for i,r in enumerate(items[start:start+2])])
        new=collate([(r[1],i) for i,r in enumerate(items[start:start+2])])
        torch.testing.assert_close(old_descriptor(old),context_descriptor(new),rtol=0,atol=0)
    print({'stage':'real_graph_equivalence','records':len(items),'seconds':preparation_seconds},flush=True)

    def timed(fn):
        begin,end=torch.cuda.Event(enable_timing=True),torch.cuda.Event(enable_timing=True)
        torch.cuda.synchronize();start=time.perf_counter();begin.record();value=fn();end.record();end.synchronize()
        return value,{'gpu_ms':begin.elapsed_time(end),'wall_ms':1000*(time.perf_counter()-start)}
    profiles=[]
    # Several actual physical batches; no node/edge cap or change to final config.
    for count in (2,4):
        if len(items)<count:raise ValueError('At least four explicit DEBUG records required')
        for version in ('v2.1','v2.2'):
            torch.manual_seed(42)
            model=(OldModel(oc,ob,patient_ids=['DEBUG_A','DEBUG_B']) if version=='v2.1' else
                   PromptGraphModel(cfg,base,patient_ids=['DEBUG_A','DEBUG_B'])).to(device).eval()
            old=version=='v2.1'
            batch=(old_collate([(items[i][0],i) for i in range(count)]) if old else
                   collate([(items[i][1],i) for i in range(count)]))
            batch,transfer=timed(lambda:batch.to(device))
            with torch.inference_mode(),torch.autocast('cuda',dtype=torch.bfloat16):
                model.encode_local(batch) # separate warm-up, no optimizer.
                torch.cuda.synchronize();torch.cuda.reset_peak_memory_stats()
                measurements=[]
                for repeat in range(3):
                    if old:
                        maps,dense=timed(lambda:model.local.encode_dense_maps(batch.source_patches,batch.source_index,batch.target_patches))
                        fields,graph=timed(lambda:model.local.forward_graph(batch.graph,*maps))
                    else:
                        fields,graph=timed(lambda:model.local(batch.graph));dense={'gpu_ms':0.,'wall_ms':0.}
                    del fields
                    if old:del maps
                    if repeat==0:torch.cuda.reset_peak_memory_stats()
                    result,total=timed(lambda:model.encode_local(batch))
                    del result
                    measurements.append({'cnn':dense,'node_projection_gnn_pooling':graph,'L0_total':total})
                peak=torch.cuda.max_memory_allocated()
            profiles.append({'version':version,'physical_graph_batch':count,'precision':'BF16','transfer':transfer,
                             'measurements':measurements,'peak_process_allocated_bytes':peak,
                             'parameters_2_debug_patients':sum(p.numel() for p in model.parameters()),
                             'descriptor_values_per_graph':20,'inference_only':True})
            print({'stage':'profile','version':version,'batch':count,'peak':peak,'last_ms':total['gpu_ms']},flush=True)
            del batch,model
            torch.cuda.empty_cache()

    # Synthetic DEBUG: full-width model with all L0/L1/L2 and actual loss/backward.
    _,batch=fixtures();batch=batch.to(device)
    model=PromptGraphModel(cfg,base,patient_ids=['A','B','C']).to(device).train()
    memory={k:v.to(device) if torch.is_tensor(v) else v for k,v in memory_fixture().items()}
    optimizer=torch.optim.AdamW(model.parameters(),lr=base['training']['lr'])
    before={n:p.detach().clone() for n,p in model.named_parameters()}
    torch.cuda.reset_peak_memory_stats();torch.cuda.synchronize();start=time.perf_counter()
    with torch.autocast('cuda',dtype=torch.bfloat16):
        out=model.forward_tasks(memory,model.encode_local(batch),torch.tensor([0,1,1,2],device=device))
        loss,_=prompt_loss(out,context_descriptor(batch),torch.tensor([1,-1,0,1],device=device),cfg['loss_weights'],cfg['temperature'])
    loss.backward()
    missing=[n for n,p in model.named_parameters() if p.grad is None or not torch.isfinite(p.grad).all()]
    if missing or not torch.isfinite(loss):raise RuntimeError(f'Invalid gradients: {missing}')
    optimizer.step();torch.cuda.synchronize()
    prefixes=['local.project.','local.blocks.','data_projection.','patient_labels','local_decoder.','label_decoder.']
    prefixes += [f'task.to_label.{i}.' for i in range(2)]+[f'task.to_data.{i}.' for i in range(2)]+[f'alignment.layers.{i}.' for i in range(2)]
    for prefix in prefixes:
        if not any(not torch.equal(before[n],p.detach()) for n,p in model.named_parameters() if n.startswith(prefix)):
            raise RuntimeError(f'Core module did not update: {prefix}')
    gradient={'scope':'synthetic CUDA DEBUG','parameters_3_debug_patients':sum(p.numel() for p in model.parameters()),
              'loss':float(loss.detach()),'all_parameter_gradients_finite':True,'core_updates':prefixes,
              'physical_graph_batch':4,'optimizer_steps':1,'peak_bytes':torch.cuda.max_memory_allocated(),
              'seconds':time.perf_counter()-start}
    if any(sha(args.cache_root/r)!=h for r,h in hashes.items()):raise RuntimeError('Original graph changed')
    verify_v1()
    report={'scope':'DEBUG only: real L0 comparison and synthetic full objective; no clinical performance claim',
            'release':'v2.2','gpu':torch.cuda.get_device_name(),'resources_start':resources,'resources_end':snapshot(),
            'real_graphs':[r[2] for r in items],'geometry_and_descriptor_equivalence':True,
            'preparation_seconds':preparation_seconds,'profiles':profiles,'cuda_gradient':gradient,
            'full_training':False,'full_evaluation':False,'source_identity':source_identity()}
    write_new(root/'verification.json',report)
    print(json.dumps({'verification':str(root/'verification.json'),'gradient':gradient}),flush=True)


if __name__=='__main__':main()
