"""Frozen-source inventory and isolated, non-writing bytecode lookup.

Generated bytecode is not source evidence. Only cache names mapping to a listed
Python source are recognized. Execution uses a fresh lookup prefix so ignored
snapshot caches cannot replace the verified source, including stale bytecode.
"""
from __future__ import annotations

import importlib.util
import os
from pathlib import Path

from .contracts import ContractError


def checked_snapshot_inventory(source, expected_names):
    source = Path(source)
    if source.is_symlink():
        raise ContractError('Snapshot root must not be a symlink')
    source = source.resolve()
    expected_names = set(expected_names)
    files, ignored = set(), []
    for path in source.rglob('*'):
        if path.is_symlink():
            raise ContractError(f'Snapshot symlink is not source evidence: {path.relative_to(source)}')
        if not path.is_file():
            continue
        name = path.relative_to(source).as_posix()
        if name not in expected_names and path.suffix == '.pyc' and path.parent.name == '__pycache__':
            try:
                original = Path(importlib.util.source_from_cache(str(path)))
                original_name = original.relative_to(source).as_posix()
            except (ValueError, NotImplementedError):
                original_name = None
            if original_name in expected_names and original.suffix == '.py':
                ignored.append(name)
                continue
        files.add(name)
    if files != expected_names:
        missing, unlisted = sorted(expected_names-files), sorted(files-expected_names)
        raise ContractError(f'Unlisted or missing snapshot files: {source.name}; source={source}; '
                            f'missing={missing!r}; unlisted={unlisted!r}')
    return dict(files=files, ignored_bytecode=sorted(ignored))


def isolated_snapshot_bytecode_env(cache_lookup):
    """Leave existing caches intact; never look them up or create replacement pyc.

    The fresh prefix belongs to the current invocation/request. Its nonexistence
    is mandatory: neither a previous cache nor a symlink may become executable.
    """
    lookup = Path(cache_lookup)
    if lookup.is_symlink() or lookup.exists():
        raise ContractError('Isolated bytecode lookup must be a new non-existing path')
    lookup = lookup.resolve()
    return dict(os.environ, PYTHONDONTWRITEBYTECODE='1', PYTHONPYCACHEPREFIX=str(lookup))
