const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
const fs=require('fs');
const folder=process.argv[2];
if(!folder)throw Error('Explicit task-owned result folder required');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:1040,height:1650}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file:///'+path.resolve(folder,'preview.html').replace(/\\/g,'/'));
  const frame=page.frameLocator('iframe'),root=frame.locator('#cnn-sparse-budget-20261002');
  await frame.locator('#cnn-sparse-budget-20261002[data-ready="true"]').waitFor();
  const record={ready:true,errors,checks:[]};
  const check=(name,condition)=>{if(!condition)throw Error(name);record.checks.push(name);};
  const canvases=root.locator('canvas');
  check('three simultaneous actual budget graphs',await canvases.count()===3);
  const counts=await canvases.evaluateAll(xs=>xs.map(x=>Number(x.dataset.nodeCount)));
  check('actual node counts49/97/193',JSON.stringify(counts)==='[49,97,193]');
  const scales=await canvases.evaluateAll(xs=>xs.map(x=>Number(x.dataset.scaleMm)));
  check('same native-mm camera scale',scales.every(x=>Math.abs(x-scales[0])<1e-9));
  check('all original P plus displayed U options',await frame.locator('#csb-candidate option').count()===8);
  check('DEBUG weight provenance visible',(await frame.locator('#csb-source').innerText()).includes('DEBUG'));
  check('measured coverage and cost rows',await frame.locator('#csb-metrics tr').count()===3);
  const images=()=>canvases.evaluateAll(xs=>xs.map(x=>x.toDataURL()));
  const original=await images();
  await root.screenshot({path:path.join(folder,'local.png')});
  await frame.locator('#csb-candidate').selectOption('0');
  await page.waitForTimeout(160);
  check('P/U changes all three actual graphs',(await images()).every((x,i)=>x!==original[i]));
  await root.screenshot({path:path.join(folder,'observed.png')});
  await frame.locator('#csb-node').selectOption('2:129');
  check('node exact native-mm detail',(await frame.locator('#csb-node-detail').innerText()).includes('mm'));
  const before=await images();
  await frame.locator('#csb-yaw').fill('-65');
  await frame.locator('#csb-yaw').dispatchEvent('input');
  await page.waitForTimeout(160);
  check('rotation changes all three graphs',(await images()).every((x,i)=>x!==before[i]));
  await frame.locator('#csb-side').selectOption('donor');
  await page.waitForTimeout(160);
  check('Donor selection synchronized',await root.getAttribute('data-side')==='donor');
  await root.screenshot({path:path.join(folder,'donor.png')});
  await frame.locator('#csb-side').selectOption('recipient');
  await frame.locator('#csb-view').selectOption('full');
  await page.waitForTimeout(160);
  const full=await images();
  check('full liver location view synchronized',full.every((x,i)=>x!==before[i]));
  await root.screenshot({path:path.join(folder,'full-liver.png')});
  await frame.locator('#csb-tumor').uncheck();
  await page.waitForTimeout(160);
  check('original tumor overlay toggle',(await images()).some((x,i)=>x!==full[i]));
  await page.setViewportSize({width:360,height:2600});
  await page.waitForTimeout(160);
  check('mobile no horizontal overflow',await root.evaluate(r=>r.scrollWidth<=r.clientWidth+2));
  await root.screenshot({path:path.join(folder,'mobile.png')});
  check('no browser runtime errors',errors.length===0);
  await browser.close();
  fs.writeFileSync(path.join(folder,'browser_checks.json'),JSON.stringify(record,null,2));
  console.log(JSON.stringify(record));
})().catch(e=>{console.error(e);process.exitCode=1;});
