const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
const folder=process.argv[2];
if(!folder)throw Error('Fresh task-owned preview folder required');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:1040,height:1800}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file:///'+path.resolve(folder,'preview.html').replace(/\\/g,'/'));
  const frame=page.frameLocator('iframe'),root=frame.locator('#v1-relay-sparse-20261002');
  await frame.locator('#v1-relay-sparse-20261002[data-ready="true"]').waitFor();
  const checks=[],check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};
  const canvases=root.locator('canvas'),values=name=>canvases.evaluateAll((xs,n)=>xs.map(x=>Number(x.dataset[n])),name),snapshot=()=>canvases.evaluateAll(xs=>xs.map(x=>x.toDataURL()));
  check('three simultaneous actual pair graphs',await canvases.count()===3);
  check('seed count is not a hidden final node cap',(await values('nodeCount')).every((v,i)=>v>[98,194,386][i]));
  check('all displayed repaired pairs connected',(await values('components')).every(v=>v===1));
  check('no displayed isolated nodes',(await values('isolatedNodes')).every(v=>v===0));
  check('actual native-parent polylines drawn',(await values('pathEdges')).every(v=>v>0));
  check('relay nodes distinct from original seeds',(await values('relayNodes')).every(v=>v>0));
  check('cross relations present',(await values('crossCount')).every(v=>v>0));
  check('common original mm scale',(await values('scaleMm')).every((v,i,a)=>Math.abs(v-a[0])<1e-8));
  check('original P5 and displayed U3 selectable',await frame.locator('#vrs-candidate option').count()===8);
  check('DEBUG weight provenance visible',(await frame.locator('#vrs-provenance').innerText()).includes('DEBUG'));
  await root.screenshot({path:path.join(folder,'relayed.png')});
  const before=await snapshot();await frame.locator('#vrs-candidate').selectOption('0');await page.waitForTimeout(120);
  check('original observed candidate changes graphs',(await snapshot()).every((v,i)=>v!==before[i]));
  await frame.locator('#vrs-node').selectOption('2:200');await page.waitForTimeout(120);
  check('selected node exact native and relative mm shown',(await frame.locator('#vrs-detail').innerText()).includes('상대 mm'));
  check('selection survives saved-state echo',await frame.locator('#vrs-node').inputValue()==='2:200');
  check('original GT contours visible',(await values('gtSegments')).every(v=>v>0));
  const gt=await snapshot();await frame.locator('#vrs-tumor').uncheck();await page.waitForTimeout(120);
  check('GT toggle changes only annotation',(await values('gtSegments')).every(v=>v===0)&&(await snapshot()).every((v,i)=>v!==gt[i]));
  await frame.locator('#vrs-tumor').check();await frame.locator('#vrs-relation').selectOption('cross');await page.waitForTimeout(120);
  const cross=await values('crossCount');
  check('cross filter draws exact actual cross edges',(await values('shownEdges')).every((v,i)=>v===cross[i]));
  check('cross filter does not depict native parent paths',(await values('pathEdges')).every(v=>v===0));
  await root.screenshot({path:path.join(folder,'cross-only.png')});
  await frame.locator('#vrs-model').selectOption('baseline');await frame.locator('#vrs-relation').selectOption('all');await page.waitForTimeout(120);
  check('previous actual seed-only node counts preserved',JSON.stringify(await values('nodeCount'))==='[98,194,386]');
  check('previous disconnected components visible',(await values('components')).every(v=>v>1));
  check('previous isolation visible',(await values('isolatedNodes')).every(v=>v>0));
  check('previous typed cross relations remain actual',(await values('crossCount')).every(v=>v>0));
  check('baseline has no invented relay paths',(await values('pathEdges')).every(v=>v===0));
  await root.screenshot({path:path.join(folder,'baseline.png')});
  await frame.locator('#vrs-model').selectOption('relational');await page.waitForTimeout(120);const initial=await snapshot();
  await frame.locator('#vrs-yaw').fill('-50');await frame.locator('#vrs-yaw').dispatchEvent('input');await page.waitForTimeout(120);
  check('3D camera rotates all graphs',(await snapshot()).every((v,i)=>v!==initial[i]));
  await frame.locator('#vrs-yaw').fill('12');await frame.locator('#vrs-yaw').dispatchEvent('input');
  const normalScale=await values('scaleMm');
  await frame.locator('#vrs-zoom').fill('125');await frame.locator('#vrs-zoom').dispatchEvent('input');await page.waitForTimeout(120);
  check('zoom uses the same physical scale in all three panels',(await values('scaleMm')).every((v,i)=>Math.abs(v/normalScale[i]-1.25)<1e-8));
  await frame.locator('#vrs-zoom').fill('100');await frame.locator('#vrs-zoom').dispatchEvent('input');
  await frame.locator('#vrs-type').selectOption('target_context_neighbor');await page.waitForTimeout(120);
  const exported=JSON.parse(fs.readFileSync(path.join(folder,'../visual_payload.json'),'utf8'));
  const typedCounts=exported.budgets.map(b=>b.variants.relational.candidates[0].joint.edges.filter(e=>e[2]==='target_context_neighbor').length);
  check('actual typed context filter draws the exact exported relation and keeps native paths',(await values('pathEdges')).every(v=>v>0)&&JSON.stringify(await values('shownEdges'))===JSON.stringify(typedCounts));
  await frame.locator('#vrs-type').selectOption('all');
  await page.setViewportSize({width:360,height:3200});await page.waitForTimeout(120);
  check('mobile no horizontal overflow',await root.evaluate(r=>r.scrollWidth<=r.clientWidth+2));
  await root.screenshot({path:path.join(folder,'mobile.png')});
  check('no browser runtime errors',errors.length===0);
  fs.writeFileSync(path.join(folder,'browser_checks.json'),JSON.stringify({checks,errors},null,2));
  console.log(JSON.stringify({checks,errors}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
