const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
const fs=require('fs');
const folder=process.argv[2];
if(!folder)throw Error('Explicit task-owned evidence folder required');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:1040,height:1600}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file:///'+path.resolve(folder,'preview.html').replace(/\\/g,'/'));
  const frame=page.frameLocator('iframe'),root=frame.locator('#cnn-sparse-graph-20261002');
  await frame.locator('#cnn-sparse-graph-20261002[data-ready="true"]').waitFor();
  const record={ready:true,errors,checks:[]};
  const check=(name,condition)=>{if(!condition)throw Error(name);record.checks.push(name)};
  check('original P and U options',await frame.locator('#csg-candidate option').count()===8);
  check('node/edge counts visible',(await frame.locator('#csg-recipient-count').innerText()).includes('49 nodes'));
  check('DEBUG weight provenance',(await frame.locator('#csg-source').innerText()).includes('DEBUG'));
  const image=()=>frame.locator('#csg-recipient-canvas').evaluate(c=>c.toDataURL());
  const initial=await image();
  await root.screenshot({path:path.join(folder,'local.png')});
  await frame.locator('#csg-candidate').selectOption('0');
  await page.waitForTimeout(150);
  check('P/U actual scene changes',initial!==await image());
  await root.screenshot({path:path.join(folder,'observed.png')});
  await frame.locator('#csg-node').selectOption('recipient:17');
  check('exact native-mm node details',(await frame.locator('#csg-node-detail').innerText()).includes('mm'));
  const beforeRotate=await image();
  await frame.locator('#csg-yaw').fill('-70');
  await frame.locator('#csg-yaw').dispatchEvent('input');
  await page.waitForTimeout(150);
  check('3D rotation works',beforeRotate!==await image());
  await frame.locator('#csg-view').selectOption('full');
  await page.waitForTimeout(150);
  const full=await image();
  check('full liver view differs',full!==beforeRotate);
  await root.screenshot({path:path.join(folder,'full-liver.png')});
  await frame.locator('#csg-tumor').uncheck();
  await page.waitForTimeout(150);
  check('original tumor overlay toggle',full!==await image());
  await page.setViewportSize({width:360,height:2200});
  await page.waitForTimeout(150);
  check('mobile no horizontal overflow',await root.evaluate(r=>r.scrollWidth<=r.clientWidth+2));
  await root.screenshot({path:path.join(folder,'mobile.png')});
  check('no browser runtime errors',errors.length===0);
  await browser.close();
  fs.writeFileSync(path.join(folder,'browser_checks.json'),JSON.stringify(record,null,2));
  console.log(JSON.stringify(record));
})().catch(e=>{console.error(e);process.exitCode=1;});
